#!/bin/bash

alias python='python3'
alias rgr='ranger'
alias oo='xset dpms force off #Turn off the screen'
alias c='calcurse'
alias y='yes | '
alias update-config-termux='. ~/github/linux-config/termux/update'
alias update-all='. ~/github/linux-config/update-all'

# config files
alias cfr='vim $HOME/.config/ranger/rc.conf'
alias cft='vim $HOME/github/linux-config/termux/termux.properties'
