#!/bin/bash

alias python='python3'
alias rgr='ranger'
alias oo='xset dpms force off'  #Turn off the screen
alias c='calcurse'
alias y='yes | '
alias update-config-termux='. ~/github/linux-config/termux/update'
alias update-all='. ~/github/linux-config/update-all'

# config files -----------------------------------------------------------------
alias cfr='vim $HOME/.config/ranger/rc.conf'
alias cft='vim $HOME/github/linux-config/termux/termux.properties'
alias cfv='vim $HOME/github/linux-config/vim/vimrc'
alias hours='python3 $GIT/hours/hours-calculation.py'

# disk listing -----------------------------------------------------------------
alias mdisk="sudo fdisk -l | grep 'Disk /dev/sd'"

# git aliases ------------------------------------------------------------------
alias gh="git logp"
alias gpad="git push origin dev && git push server dev"
alias gcobare="git symbolic-ref HEAD"

# docker aliases ---------------------------------------------------------------
alias dps="docker ps"
alias dpsa="docker ps -a"
alias drm="docker rm"
alias dsp="docker stop"
alias ds="docker start"
alias di="docker image"
alias db="docker build"
alias dl="docker logs"
alias dn="docker network"
alias de="docker exec -it"

# react-native aliases
alias rnra="react-native run-android"
alias rns="react-native start"
