#!/bin/bash

echo "Configuring Docker CE ----------------------------------------------------"
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
sudo apt update
apt-cache search docker-ce
sudo apt install docker-ce docker-ce-cli containerd.io

sudo groupadd docker
sudo usermod -a -G docker $USER

sudo snap install postbird