#!/bin/bash

echo "install zsh"

sudo apt install zsh -y

echo "install oh-my-zsh------------------------------------"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "install zplugin--------------------------------------"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"

echo "install spaceship theme------------------------------"

local_repo=$HOME/.oh-my-zsh/custom/themes/spaceship-prompt

git clone "https://github.com/denysdovhan/spaceship-prompt.git" $local_repo
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" $local_repo

echo "done -------------------------------------------------"
