#!/bin/bash

[[ -d $HOME/.PhpStorm2019.3/config/keymaps ]] || mkdir $HOME/.PhpStorm2019.3/config/keymaps

rm $HOME/.PhpStorm*/config/keymaps/*

ln -s $LINUX_CONFIG_HOME/jetbrains/* $HOME/.PhpStorm*/config/keymaps/
