#!/usr/bin/python3

import os
import subprocess

# command_text = 'time touch del.newfile'
# command_output = os.popen(command_text).read()
# os.system(command)
url = "https://extensions.gnome.org/extension-data/putWindowclemens.lab21.org.v26.shell-extension.zip"
result = subprocess.run(['basename', url], stdout=subprocess.PIPE).stdout.decode('utf-8')

print(result.strip())

extensions_repos = [
  "https://extensions.gnome.org/extension-data/putWindowclemens.lab21.org.v26.shell-extension.zip",
  "https://extensions.gnome.org/extension-data/gnome-shell-screenshotttll.de.v40.shell-extension.zip",
  "https://extensions.gnome.org/extension-data/dash-to-dockmicxgx.gmail.com.v65.shell-extension.zip",
  "https://extensions.gnome.org/extension-data/window-corner-previewfabiomereu.it.v4.shell-extension.zip",
]

extension_names = [
  "putWindow@clemens.lab21.org",
  "gnome-shell-screenshot@ttll.de",
  "dash-to-dock@micxgx.gmail.com",
  "window-corner-preview@fabiomereu.it",
]

index = 0
for url in extensions_repos:

  filename=os.popen('basename "$url"').read()

  cmd = ['basename', '"$url"']

  # print(url, '-', filename)

  index += 1
