#!/bin/bash

LINUX_CONFIG_HOME=$HOME/linux-config/

[ -f $HOME/.profile ] && rm $HOME/.profile && echo 'Removing existing .profile'

ln -s $LINUX_CONFIG_HOME/profile/profile $HOME/.profile && echo 'Linking new .profile'

