#!/bin/bash

# ---- Piano notes source
# http://theremin.music.uiowa.edu/MISpiano.html

# ---- Files need to be wav. Coverter:
# https://www.media.io/br/

# play is a command from the sox library
# sudo apt install sox

d4='D4.wav'
a4='A4.wav'
f4='F4.wav'
e4='E4.wav'

timeout 6s play $d4 &

./dafe-main && ./dafe-main && ./dafe-main
